---
- name: Create a VM in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a VM
      ec2:
        aws_access_key: "{{ _aws_access_key_ }}"
        aws_secret_key: "{{ _aws_secret_key_ }}"
        key_name: "{{ _key_name_ }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        wait: true
        group: "{{ security_group }}"
        instance_tags:
          Name: RHEL-VM
        count: 1
      register: ec2
    - name: Add new instance to host group
      ansible.builtin.add_host:
        hostname: "{{ _hostname_ }}"
        groupname: "{{ ec2.instances }}"
- name: Configure RHEL-VM
  hosts: launched
  become: true
  gather_facts: false
  tasks:
    - name: Wait for the instance to become reachable over SSH
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
    - name: Install Python
      ansible.builtin.raw: test -e /usr/bin/python || (yum -y update && yum install -y python3)
    - name: Install Ansible
      ansible.builtin.raw: test -e /usr/bin/ansible || (yum -y update && yum install -y ansible)
    - name: Install git
      ansible.builtin.raw: test -e /usr/bin/git || yum install -y git
    - name: Install vim
      ansible.builtin.raw: test -e /usr/bin/vim || yum install -y vim
    - name: Install tree
      ansible.builtin.raw: test -e /usr/bin/tree || yum install -y tree
    - name: Install wget
      ansible.builtin.raw: test -e /usr/bin/wget || yum install -y wget
    - name: Install net-tools
      ansible.builtin.raw: test -e /usr/bin/netstat || yum install -y net-tools
    - name: Install telnet
      ansible.builtin.raw: test -e /usr/bin/telnet || yum install -y telnet
    - name: Install bind-utils
      ansible.builtin.raw: test -e /usr/bin/dig || yum install -y bind-utils
    - name: Install htop
      ansible.builtin.raw: test -e /usr/bin/htop || yum install -y htop
    - name: Install tmux
      ansible.builtin.raw: test -e /usr/bin/tmux || yum install -y tmux
    - name: Install nano
      ansible.builtin.raw: test -e /usr/bin/nano || yum install -y nano
    - name: Install unzip
      ansible.builtin.raw: test -e /usr/bin/unzip || yum install -y unzip
    - name: Install zip
      ansible.builtin.raw: test -e /usr/bin/zip || yum install -y zip
    - name: Install bzip2
      ansible.builtin.raw: test -e /usr/bin/bzip2 || yum install -y bzip2
    - name: Install rsync
      ansible.builtin.raw: test -e /usr/bin/rsync || yum install -y rsync
    - name: Install lsof
      ansible.builtin.raw: test -e /usr/bin/lsof || yum install -y lsof
    - name: Install nc
      ansible.builtin.raw: test -e /usr/bin/nc || yum install -y nc
    - name: Install jq
      ansible.builtin.raw: test -e /usr/bin/jq || yum install -y jq
    - name: Install curl
      ansible.builtin.raw: test -e /usr/bin/curl || yum install -y curl
    - name: Install wget
      ansible.builtin.raw: test -e /usr/
